# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='area',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party_number',
            field=models.IntegerField(default=1),
        ),
    ]
